import { Quotation, Product, Warehouse, GovernanceRule, UserAccount } from './types'

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'LP-14',
    name: 'Laptop Pro 14',
    category: 'Hardware',
    type: 'one_time',
    unitPrice: 1200,
    costPrice: 840,
    stock: 55,
    description: 'High performance business and workstation laptop (14-inch).',
  },
  {
    id: '2',
    sku: 'LP-16',
    name: 'Laptop Pro 16',
    category: 'Hardware',
    type: 'one_time',
    unitPrice: 1550,
    costPrice: 1020,
    stock: 42,
    description: 'High performance business and workstation laptop (16-inch).',
  },
  {
    id: '3',
    sku: 'LP-18',
    name: 'Laptop Pro 18',
    category: 'Hardware',
    type: 'one_time',
    unitPrice: 2100,
    costPrice: 1350,
    stock: 42,
    description: 'Ultra workstation laptop (18-inch).',
  },
  {
    id: '4',
    sku: 'MB-24',
    name: 'Monitor Basic 24',
    category: 'Hardware',
    type: 'one_time',
    unitPrice: 220,
    costPrice: 150,
    stock: 26,
    description: 'Ultra-sharp business and professional monitor (24-inch).',
  },
  {
    id: '5',
    sku: 'MP-27',
    name: 'Monitor Pro 27',
    category: 'Hardware',
    type: 'one_time',
    unitPrice: 380,
    costPrice: 240,
    stock: 26,
    description: 'Ultra-sharp professional monitor (27-inch 4K).',
  },
  {
    id: '7',
    sku: 'BC-1Y',
    name: 'Basic Care 1yr',
    category: 'Services',
    type: 'recurring',
    unitPrice: 120,
    costPrice: 40,
    stock: 999,
    description: 'Annual basic warranty support plan.',
  },
  {
    id: '19',
    sku: 'SRV-SETUP',
    name: 'Onsite Setup Service',
    category: 'Services',
    type: 'one_time',
    unitPrice: 450,
    costPrice: 200,
    stock: 999,
    description: 'Professional on-site hardware installation and configuration.',
  },
  {
    id: '22',
    sku: 'WRT-EXT',
    name: 'Extended Warranty',
    category: 'Services',
    type: 'recurring',
    unitPrice: 180,
    costPrice: 50,
    stock: 999,
    description: 'Two-year extended hardware replacement warranty.',
  },
]

export const INITIAL_GOVERNANCE: GovernanceRule = {
  tierLimits: {
    Bronze: 5,
    Silver: 10,
    Gold: 15,
    Platinum: 20,
  },
  categoryLimits: {
    Hardware: 15,
    Software: 25,
    Services: 10,
  },
  approvalLevels: {
    managerThreshold: 15,
    financeThreshold: 20,
  },
}

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: '1',
    name: 'Mumbai Central Warehouse',
    location: 'Mumbai, Maharashtra',
    inventory: {
      '1': 55,
      '2': 42,
      '4': 26,
    },
  },
  {
    id: '2',
    name: 'Bangalore Distribution Center',
    location: 'Bangalore, Karnataka',
    inventory: {
      '1': 42,
      '2': 35,
      '5': 23,
    },
  },
  {
    id: '3',
    name: 'Delhi Fulfillment Center',
    location: 'Delhi, Delhi',
    inventory: {
      '1': 30,
      '2': 25,
      '4': 18,
    },
  },
]

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'Q-1042',
    dealName: 'Acme Corp — Hardware & Setup Expansion - $2,854',
    customerName: 'Acme Corp',
    customerTier: 'ENTERPRISE',
    salesRep: 'Aarav Sharma',
    status: 'Under Review',
    createdAt: '2026-03-01',
    validUntil: '2026-04-01',
    blendedRiskScore: 78,
    riskLevel: 'Low',
    items: [
      {
        id: '1',
        productId: '1',
        name: 'Laptop Pro 14',
        category: 'Hardware',
        type: 'one_time',
        qty: 2,
        unitPrice: 1200,
        discountPct: 12.0,
        costPrice: 840,
      },
      {
        id: '2',
        productId: '19',
        name: 'Onsite Setup Service',
        category: 'Services',
        type: 'one_time',
        qty: 1,
        unitPrice: 450,
        discountPct: 18.0,
        costPrice: 200,
      },
      {
        id: '3',
        productId: '22',
        name: 'Extended Warranty',
        category: 'Services',
        type: 'recurring',
        qty: 1,
        unitPrice: 180,
        discountPct: 10.0,
        costPrice: 50,
      },
    ],
  },
  {
    id: 'Q-1002',
    dealName: 'Nova Systems — Workstation Upgrade - $987',
    customerName: 'Nova Systems',
    customerTier: 'MID_MARKET',
    salesRep: 'Aarav Sharma',
    status: 'Under Review',
    createdAt: '2026-03-01',
    validUntil: '2026-04-01',
    blendedRiskScore: 82,
    riskLevel: 'Low',
    items: [
      {
        id: '4',
        productId: '4',
        name: 'Monitor Basic 24',
        category: 'Hardware',
        type: 'one_time',
        qty: 4,
        unitPrice: 220,
        discountPct: 10.0,
        costPrice: 150,
      },
    ],
  },
  {
    id: 'Q-1004',
    dealName: 'BluePeak Retail — POS Terminal Setup - $975',
    customerName: 'BluePeak Retail',
    customerTier: 'ENTERPRISE',
    salesRep: 'Priya Mehta',
    status: 'Approved',
    createdAt: '2026-03-01',
    validUntil: '2026-04-01',
    blendedRiskScore: 90,
    riskLevel: 'Low',
    items: [
      {
        id: '5',
        productId: '1',
        name: 'Laptop Pro 14',
        category: 'Hardware',
        type: 'one_time',
        qty: 1,
        unitPrice: 1200,
        discountPct: 15.0,
        costPrice: 840,
      },
    ],
  },
]

export const INITIAL_USERS: UserAccount[] = [
  { id: 1, name: 'Aarav Sharma', email: 'sales1@dealflow360.demo', role: 'Sales Representative', status: 'Active' },
  { id: 2, name: 'Priya Mehta', email: 'sales2@dealflow360.demo', role: 'Sales Representative', status: 'Active' },
  { id: 3, name: 'Rohan Kapoor', email: 'manager1@dealflow360.demo', role: 'Sales Manager', status: 'Active' },
  { id: 4, name: 'Ananya Iyer', email: 'manager2@dealflow360.demo', role: 'Sales Manager', status: 'Active' },
  { id: 5, name: 'Vikram Malhotra', email: 'finance1@dealflow360.demo', role: 'Finance/Operations', status: 'Active' },
  { id: 6, name: 'Kavita Rao', email: 'customer1@acme.demo', role: 'Customer Portal User', status: 'Active' },
  { id: 7, name: 'Sameer Joshi', email: 'customer2@novasystems.demo', role: 'Customer Portal User', status: 'Active' },
  { id: 8, name: 'Rajesh Varma', email: 'admin@dealflow360.demo', role: 'Admin', status: 'Active' },
]
